/gazebo_ros_control:
  pid_gains:
    shoulder_pan_joint:
      p: 500.0
      i: 0.0
      d: 50.0
      i_clamp_min: 0
      i_clamp_max: 0
    shoulder_lift_joint:
      p: 2500.0
      i: 0.0
      d: 100.0
      i_clamp_min: 0
      i_clamp_max: 0
    elbow_joint:
      p: 2500
      i: 0.0
      d: 100.0
      i_clamp_min: 0
      i_clamp_max: 0
    wrist_1_joint:
      p: 500.0
      i: 0.0
      d: 10.0
      i_clamp_min: 0
      i_clamp_max: 0
    wrist_2_joint:
      p: 500.0
      i: 0.0
      d: 10.0
      i_clamp_min: 0
      i_clamp_max: 0
    wrist_3_joint:
      p: 500.0
      i: 0.0
      d: 10.0
      i_clamp_min: 0
      i_clamp_max: 0