/gazebo_ros_control:
  pid_gains:
    shoulder_pan_joint:
      p: 2500.0
      i: 0.2
      d: 100.0
      i_clamp_min: 10
      i_clamp_max: 10
    shoulder_lift_joint:
      p: 2500.0
      i: 0.2
      d: 100.0
      i_clamp_min: 10
      i_clamp_max: 10
    elbow_joint:
      p: 2500
      i: 0.2
      d: 50.0
      i_clamp_min: 10
      i_clamp_max: 10
    wrist_1_joint:
      p: 1000.0
      i: 0.2
      d: 25.0
      i_clamp_min: 5
      i_clamp_max: 5
    wrist_2_joint:
      p: 1000.0
      i: 0.7
      d: 25.0
      i_clamp_min: 5
      i_clamp_max: 5
    wrist_3_joint:
      p: 1000.0
      i: 0.7
      d: 25.5
      i_clamp_min: 5
      i_clamp_max: 5